---
title: "DriftAndReward final"
author: "Rasmus Brostrøm"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(ggplot2)
library(dplyr)
library(stats)
library(boot)
library(plotrix)
library(nlstools)
library(kableExtra)
```

```{r}
#setwd("C:/Projects/Data-driven-algorithms-for-Impulse-control-problem-Thesis")
setwd("C:/Uni/Data-driven-algorithms-for-Impulse-control-problem-Thesis")
data <- read.csv("./SimulationData/DriftAndRewardData/DriftsAndRewards.csv")
thresholds <- read.csv("./SimulationData/DriftAndRewardData/DriftsAndRewardsThresholds.csv")
```

Filtering, so we only have the data that we want to look at

```{r}
DriftAndReward <- data %>% filter(zeroVal == 0.99)
DriftAndRewardThresholds <- thresholds %>% filter(zeroVal == 0.99)
```

Average data

```{r}
avgDriftAndReward <- DriftAndReward %>% group_by(T, C, power) %>% 
                          summarise(avgRegret = mean(regret),
                                    sdRegret = sd(regret),
                                    varRegret = var(regret),
                                    avgST = mean(S_T),
                                    seST = std.error(S_T),
                                    avgDataDecisions = mean(dataStratNrDecisions),
                                    seDataDecisions =std.error(dataStratNrDecisions),
                                    avgOptDecisions = mean(optNrDecisions),
                                    seOptDecisions = std.error(optNrDecisions),
                                    .groups = "drop")

avgDriftAndReward$C = as.factor(avgDriftAndReward$C)
avgDriftAndReward$power = as.factor(avgDriftAndReward$power)
avgDriftAndReward$CText = paste0("Drift slope = ", avgDriftAndReward$C)
avgDriftAndReward$pText = paste0("Payoff power = ", avgDriftAndReward$power)
```

Average data per time unit

```{r}
avgDriftAndRewardPerTime <- DriftAndReward %>%
  mutate(regretPerTime = regret/T) %>%
  group_by(T, C, power) %>% 
  summarise(avgRegret = mean(regretPerTime),
            sdRegret = sd(regretPerTime),
            varRegret = var(regretPerTime),
            avgST = mean(S_T),
            seST = std.error(S_T),
            avgDataDecisions = mean(dataStratNrDecisions),
            seDataDecisions =std.error(dataStratNrDecisions),
            avgOptDecisions = mean(optNrDecisions),
            seOptDecisions = std.error(optNrDecisions),
            .groups = "drop")

avgDriftAndRewardPerTime$C = as.factor(avgDriftAndRewardPerTime$C)
avgDriftAndRewardPerTime$power = as.factor(avgDriftAndRewardPerTime$power)
avgDriftAndRewardPerTime$CText = paste0("Drift slope = ", avgDriftAndRewardPerTime$C)
avgDriftAndRewardPerTime$pText = paste0("Payoff power = ", avgDriftAndRewardPerTime$power)
```


# Average and variance of cumulative regret

```{r}
ggplot(avgDriftAndReward, aes(x=T, group=CText))+
  geom_line(aes(y=avgRegret, color=CText))+
  facet_wrap(~pText, nrow = 2, scales = "free")+
  ylab("Average cumulative regret")+
  ggtitle("Average cumulative regret for drift and payoff functions")+
  labs(color = "Drift slope")+
  theme_bw()+
  scale_y_continuous(breaks = scales::pretty_breaks(n = 5))+
  theme(plot.margin = unit(rep(1.5, 4),"mm"),
        legend.justification= c(1, 0), 
        legend.position = c(0.1, 0.9),
        legend.key = element_blank(),
        legend.title = element_blank(),
        legend.text = element_text(size=9, face = "bold"),
        legend.background = element_rect(fill=alpha(0.0001)))
```

```{r}
ggplot(avgDriftAndReward, aes(x=T, group=CText))+
  geom_line(aes(y=sdRegret, color=CText))+
  facet_wrap(~pText, nrow = 2, scales = "free")+
  ylab("Average cumulative regret")+
  ggtitle("Average cumulative regret for drift and payoff functions")+
  labs(color = "Drift slope")
```




# All plots of average regret

```{r}
avgData <- data %>%
  group_by(T, C, power, zeroVal) %>%
  summarise(avgRegret = mean(regret),
            sdRegret = sd(regret),
            varRegret = var(regret),
            avgST = mean(S_T),
            seST = std.error(S_T),
            avgDataDecisions = mean(dataStratNrDecisions),
            seDataDecisions =std.error(dataStratNrDecisions),
            avgOptDecisions = mean(optNrDecisions),
            seOptDecisions = std.error(optNrDecisions),
            .groups = "drop")

avgData$C = as.factor(avgData$C)
avgData$power = as.factor(avgData$power)
avgData$zeroVal = as.factor(avgData$zeroVal)
avgData$CText = paste0("Drift slope = ", avgData$C)
avgData$zeroValText = paste0("Payoff a-value = ", avgData$zeroVal)
avgData$pText = paste0("Payoff power = ", avgData$power)
```

Average cumulative regret plot

```{r}
ggplot(avgData, aes(x=T, group=CText))+
  geom_line(aes(y=avgRegret, color=CText))+
  ylab("Average cumulative regret")+
  ggtitle("Average cumulative regret for drift and payoff functions")+
  labs(color = "Drift Slope")+
  facet_grid(pText ~ zeroValText, scales="free")+
  theme_bw()+
  scale_y_continuous(breaks = scales::pretty_breaks(n = 5))+
  theme(plot.margin = unit(rep(1, 4),"pt"),
        legend.justification= c(1, 0), 
        legend.position = c(0.18, 0.9),
        legend.key = element_blank(),
        legend.title = element_blank(),
        legend.text = element_text(size=9, face = "bold"),
        legend.margin = margin(0, 0, 0, 0),
        legend.key.spacing.x = unit(0, "pt"),
        legend.key.spacing.y = unit(-6, "pt"),
        legend.spacing.y = unit(-5, "pt"),
        legend.box.spacing = unit(0, "pt"),
        legend.background = element_rect(fill=alpha(0.0001)))
```

Variance of cumulative regret plot

```{r}
ggplot(avgData, aes(x=T, group=CText))+
  geom_line(aes(y=sdRegret, color=CText))+
  ylab("Standard deviation of cumulative regret")+
  ggtitle("Standard deviation of cumulative regret for drift and payoff functions")+
  labs(color = "Drift Slope")+
  facet_grid(pText ~ zeroValText, scales="free")+
  theme_bw()+
  scale_y_continuous(breaks = scales::pretty_breaks(n = 5))+
  theme(plot.margin = unit(rep(1, 4),"pt"),
        legend.justification= c(1, 0), 
        legend.position = c(0.18, 0.9),
        legend.key = element_blank(),
        legend.title = element_blank(),
        legend.text = element_text(size=9, face = "bold"),
        legend.margin = margin(0, 0, 0, 0),
        legend.key.spacing.x = unit(0, "pt"),
        legend.key.spacing.y = unit(-6, "pt"),
        legend.spacing.y = unit(-5, "pt"),
        legend.box.spacing = unit(0, "pt"),
        legend.background = element_rect(fill=alpha(0.0001)))
```

# Plots of average regret per time unit

```{r}
avgDataPerTime <- data %>%
  mutate(regretPerTime = regret/T) %>% 
  group_by(T, C, power, zeroVal) %>%
  summarise(avgRegret = mean(regretPerTime),
            sdRegret = sd(regretPerTime),
            varRegret = var(regretPerTime),
            avgST = mean(S_T),
            seST = std.error(S_T),
            avgDataDecisions = mean(dataStratNrDecisions),
            seDataDecisions =std.error(dataStratNrDecisions),
            avgOptDecisions = mean(optNrDecisions),
            seOptDecisions = std.error(optNrDecisions),
            .groups = "drop")

avgDataPerTime$C = as.factor(avgDataPerTime$C)
avgDataPerTime$power = as.factor(avgDataPerTime$power)
avgDataPerTime$zeroVal = as.factor(avgDataPerTime$zeroVal)
avgDataPerTime$CText = paste0("Drift slope = ", avgDataPerTime$C)
avgDataPerTime$zeroValText = paste0("Payoff a-value = ", avgDataPerTime$zeroVal)
avgDataPerTime$pText = paste0("Payoff power = ", avgDataPerTime$power)
```

Average cumulative regret plot

```{r}
ggplot(avgDataPerTime, aes(x=T, group=CText))+
  geom_line(aes(y=avgRegret, color=CText))+
  ylab("Average cumulative regret per time unit")+
  ggtitle("Average cumulative regret per time unit for drift and payoff functions")+
  labs(color = "Drift Slope")+
  facet_grid(pText ~ zeroValText, scales="free")+
  theme_bw()+
  scale_y_continuous(breaks = scales::pretty_breaks(n = 5))+
  theme(plot.margin = unit(rep(1, 4),"pt"),
        legend.justification= c(1, 0), 
        legend.position = c(0.18, 0.9),
        legend.key = element_blank(),
        legend.title = element_blank(),
        legend.text = element_text(size=9, face = "bold"),
        legend.margin = margin(0, 0, 0, 0),
        legend.key.spacing.x = unit(0, "pt"),
        legend.key.spacing.y = unit(-6, "pt"),
        legend.spacing.y = unit(-5, "pt"),
        legend.box.spacing = unit(0, "pt"),
        legend.background = element_rect(fill=alpha(0.0001)))
```

Variance of cumulative regret plot

```{r}
ggplot(avgDataPerTime, aes(x=T, group=CText))+
  geom_line(aes(y=sdRegret, color=CText))+
  ylab("Standard deviation of cumulative regret")+
  ggtitle("Standard deviation of cumulative regret for drift and payoff functions")+
  labs(color = "Drift Slope")+
  facet_grid(pText ~ zeroValText, scales="free")+
  theme_bw()+
  scale_y_continuous(breaks = scales::pretty_breaks(n = 5))+
  theme(plot.margin = unit(rep(1, 4),"pt"),
        legend.justification= c(1, 0), 
        legend.position = c(0.18, 0.9),
        legend.key = element_blank(),
        legend.title = element_blank(),
        legend.text = element_text(size=9, face = "bold"),
        legend.margin = margin(0, 0, 0, 0),
        legend.key.spacing.x = unit(0, "pt"),
        legend.key.spacing.y = unit(-6, "pt"),
        legend.spacing.y = unit(-5, "pt"),
        legend.box.spacing = unit(0, "pt"),
        legend.background = element_rect(fill=alpha(0.0001)))
```
