---
title: "MisspecificationPlots"
author: "Rasmus Brostrøm"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(ggplot2)
library(dplyr)
library(stats)
library(boot)
library(plotrix)
library(nlstools)
library(kableExtra)
library(latex2exp)
library(ggh4x)
```

```{r}
setwd("C:/Projects/Data-driven-algorithms-for-Impulse-control-problem-Thesis")
#setwd("C:/Uni/Data-driven-algorithms-for-Impulse-control-problem-Thesis")
data <- read.csv("./SimulationData/MisspecificationData/MisspecificationData.csv")
thresholds <- read.csv("./SimulationData/MisspecificationData/MisspecificationThresholdData.csv")
```

# Finding outliers in regret

```{r}
outliers <- data %>% filter(dataDriveReward < 0 | OptimalStratReward < 0)
non_outliers <- data %>% filter(dataDriveReward > 0 & OptimalStratReward > 0)
```

# Looking at outliers
```{r}
unique(outliers$driftFuncPower)

sumStatsOutliers <- outliers %>% group_by(driftFuncName, driftFuncPower) %>% 
  summarise(n = n(),
            meanRegret = mean(regret),
            maxRegret = max(regret),
            minRegret = min(regret),
            meanOptReward = mean(OptimalStratReward),
            maxOptReward = max(OptimalStratReward),
            minOptReward = min(OptimalStratReward),
            meanDataReward = mean(dataDriveReward),
            maxDataReward = max(dataDriveReward),
            minDataReward = min(dataDriveReward),
            meanOptDecisions = mean(optNrDecisions),
            meanDatadecisions = mean(dataStratNrDecisions))

sumStatsOutliers
```



# Cumulative regret for non outliers

```{r}
non_outliers <- non_outliers %>% mutate(exploitationTime = T-S_T,
                        DataStratNrDecisionsPerExploitationTime = dataStratNrDecisions/exploitationTime,
                        OptStratNrDecisionsPerTime = optNrDecisions/T)
```


```{r}
avgData <- non_outliers %>%
  group_by(T, power, driftFuncName, driftFuncPower) %>%
  summarise(avgRegret = mean(regret),
            sdRegret = sd(regret),
            varRegret = var(regret),
            avgST = mean(S_T),
            seST = std.error(S_T),
            avgDataDecisions = mean(dataStratNrDecisions),
            seDataDecisions =std.error(dataStratNrDecisions),
            avgOptDecisions = mean(optNrDecisions),
            seOptDecisions = std.error(optNrDecisions),
            avgDataDecisionsPerTime = mean(DataStratNrDecisionsPerExploitationTime),
            avgOptDecisionsPerTime = mean(OptStratNrDecisionsPerTime),
            .groups = "drop")


avgData$power = as.factor(avgData$power)
avgData$pText = paste0("Payoff power = ", avgData$power)
avgData$driftFuncName <- as.factor(avgData$driftFuncName)
avgData$driftFuncPower <- as.factor(avgData$driftFuncPower)
avgData$driftpText <- factor(paste0("Drift power = ", avgData$driftFuncPower), levels = c("Drift power = 3", "Drift power = 13"))
avgData$driftpText2 <- factor(paste0("m = ", avgData$driftFuncPower), levels = c("m = 3", "m = 13"))
```

```{r}
ggplot(avgData, aes(x=T, group=driftFuncName))+
  geom_line(aes(y=avgRegret, color=driftFuncName), size=1.2)+
  ylab("Average cumulative regret")+
  xlab("Time horizon (T)")+
  ggtitle("Average cumulative regret for misspecified drifts")+
  scale_color_manual(values = c("b1" = "#66c2a5",
                                "b2" = "#fc8d62",
                                "b3" = "#8da0cb"),
                     labels=c(TeX("$b_1$"), TeX("$b_2$"), TeX("$b_3$")))+
  labs(color = "Drift Slope")+
  facet_grid(pText ~ driftpText2, scales="free")+
  theme_bw()+
  scale_y_continuous(breaks = scales::pretty_breaks(n = 5))+
  theme(plot.title = element_text(face = "bold", size=13),
        axis.title.x = element_text(size=12),
        axis.title.y = element_text(size=12),
        strip.text = element_text(size=11),
        legend.justification= c(1, 0), 
        legend.position = c(0.08, 0.81),
        legend.key = element_blank(),
        legend.title = element_blank(),
        legend.text = element_text(size=11),
        legend.margin = margin(0, 0, 0, 0),
        legend.key.spacing.x = unit(0, "pt"),
        legend.key.spacing.y = unit(-6, "pt"),
        legend.spacing.y = unit(-5, "pt"),
        legend.box.spacing = unit(0, "pt"),
        legend.background = element_rect(fill=alpha(0.0001)))
```

```{r}
ggplot(avgData, aes(x=T, group=driftFuncName))+
  geom_line(aes(y=sdRegret, color=driftFuncName), size=1.2)+
  ylab("Standard deviation of cumulative regret")+
  xlab("Time horizon (T)")+
  ggtitle("Standard deviation of cumulative regret for misspecified drifts")+
  scale_color_manual(values = c("b1" = "#66c2a5",
                                "b2" = "#fc8d62",
                                "b3" = "#8da0cb"),
                     labels=c(TeX("$b_1$"), TeX("$b_2$"), TeX("$b_3$")))+
  labs(color = "Drift Slope")+
  ggh4x::facet_grid2(pText ~ driftpText2, scales="free_y", independent = "y")+
  theme_bw()+
  scale_y_continuous(breaks = scales::pretty_breaks(n = 5))+
  theme(plot.title = element_text(face = "bold", size=13),
        axis.title.x = element_text(size=12),
        axis.title.y = element_text(size=12),
        strip.text = element_text(size=11),
        legend.justification= c(1, 0),
        legend.position = c(0.08, 0.81),
        legend.key = element_blank(),
        legend.title = element_blank(),
        legend.text = element_text(size=11),
        legend.margin = margin(0, 0, 0, 0),
        legend.key.spacing.x = unit(0, "pt"),
        legend.key.spacing.y = unit(-6, "pt"),
        legend.spacing.y = unit(-5, "pt"),
        legend.box.spacing = unit(0, "pt"),
        legend.background = element_rect(fill=alpha(0.0001)))
```

## Calculating order of regret

```{r}
fitDriftAndRewardData <- avgData %>%
  filter(driftFuncPower == "13") %>% 
  group_by(driftFuncName, power) %>% 
  summarise(
  pow=summary(nls(avgRegret ~ I(a*T^p), start=list(p=1, a=1), trace=F))$coefficients[1,1],
  powSE=summary(nls(avgRegret ~ I(a*T^p),start=list(p=1,a=1), trace=F))$coefficients[1,2],
  powSig=summary(nls(avgRegret~I(a*T^p),start=list(p=1,a=1), trace=F))$coefficients[1,4]<0.05,
  c=summary(nls(avgRegret ~ I(a*T^p), start=list(p=1, a=1), trace=F))$coefficients[2,1],
  cSE = summary(nls(avgRegret ~ I(a*T^p), start=list(p=1,a=1), trace=F))$coefficients[2,2],
  cSig = summary(nls(avgRegret~I(a*T^p),start=list(p=1,a=1), trace=F))$coefficients[2,4]<0.05,
  .groups = "drop")

fitDriftAndRewardData$pConf <- paste0(round(fitDriftAndRewardData$pow, 3), "±", round(2*fitDriftAndRewardData$powSE, 4))
fitDriftAndRewardData$cConf <- paste0(round(fitDriftAndRewardData$c, 3), "±", round(2*fitDriftAndRewardData$cSE, 4))
```

```{r}
fitDriftAndRewardData %>% 
  pivot_wider(id_cols = driftFuncName, names_from = power, values_from = c(cConf, pConf)) %>%
  kable(align = rep("c", 5), col.names = NULL) %>% 
  kable_classic() %>% 
  add_header_above(c("Drift function", rep(c("Payoff power = 2", "Payoff power = 5"), 2))) %>% 
  add_header_above(c(" ", "Constant"=2, "Order"=2))
```

```{r}
fitDriftAndRewardData %>% 
  pivot_wider(id_cols = driftFuncName, names_from = power, values_from = c(cConf, pConf)) %>%
  kable(align = rep("c", 5), col.names = NULL, linesep="", longtable=FALSE, format="latex") %>% 
  kable_classic() %>% 
  add_header_above(c("Drift function", rep(c("Payoff power = 1", "Payoff power = 5"), 2))) %>% 
  add_header_above(c(" ", "Constant"=2, "Order"=2))
```

### Plotting the fits

```{r}
As = unique(avgData$driftFuncPower)
Sigmas = unique(avgData$driftFuncName)
powers = unique(avgData$power)

test3 <- data.frame()

for(c in As){
  for(p in powers){
    for(z in Sigmas){
      tmpData <- avgData %>% filter(driftFuncName == z & driftFuncPower == c & power == p)
      m <- nls(avgRegret ~ I(a*T^p), start=list(p=1, a=1), trace=F, data = tmpData)
      fitted_values <- fitted(m)
      attributes(fitted_values)$label <- NULL
      testNew <- data.frame(driftFuncPower=c,
                            power=p,
                            driftFuncName=z,
                            T=seq(100, 5000, by=100),
                            fittedVals = fitted_values) 

      test3 <- rbind(test3, testNew)
    }
  }
}

fittedValuesDF <- merge(avgData, test3, by=c("driftFuncPower", "power", "T", "driftFuncName"))
```

```{r}
tmpData <- fittedValuesDF %>% filter(driftFuncPower == 13)

ggplot(tmpData, aes(x=T))+
  geom_point(aes(y=avgRegret, color="Actual value"), size=1.7)+
  geom_line(aes(y=fittedVals, color="Fitted value"), size=1.2)+
  scale_color_manual(values = c("Actual value" = "#66c2a5",
                                "Fitted value"="#fc8d62"))+
  ylab("Average cumulate regret")+
  xlab("Time horizon (T)")+
  ggtitle("Fitted average cumulative regret for m=13")+
  facet_grid(pText ~ driftFuncName, scales="free")+
  theme_bw()+
  scale_y_continuous(breaks = scales::pretty_breaks(n = 5))+
  theme(plot.title = element_text(face = "bold", size=13),
        axis.title.x = element_text(size=12),
        axis.title.y = element_text(size=12),
        strip.text = element_text(size=11),
        legend.justification= c(1, 0), 
        legend.position = c(0.17, 0.88),
        legend.key = element_blank(),
        legend.title = element_blank(),
        legend.text = element_text(size=11),
        legend.margin = margin(0, 0, 0, 0),
        legend.key.spacing.x = unit(0, "pt"),
        legend.key.spacing.y = unit(-6, "pt"),
        legend.spacing.y = unit(-5, "pt"),
        legend.box.spacing = unit(0, "pt"),
        legend.background = element_rect(fill=alpha(0.0001)))
```

## Exploration times

```{r}
tmpData <- avgData %>% filter(driftpText2 == "m = 13")

ggplot(tmpData, aes(x=T))+
  geom_line(aes(y=avgST, color="Actual ST"), size=1.2)+
  geom_line(aes(y=T^{2/3}, color="Target ST"), size=1.2)+
  scale_color_manual(values = c("Actual ST" = "#66c2a5",
                                "Target ST"="#fc8d62"))+
  ylab("Average exploration time (ST)")+
  xlab("Time horizon (T)")+
  ggtitle("Average exploration time for m=13")+
  facet_grid(pText ~ driftFuncName, scales="free")+
  theme_bw()+
  scale_y_continuous(breaks = scales::pretty_breaks(n = 5))+
  theme(plot.title = element_text(face = "bold", size=13),
        axis.title.x = element_text(size=12),
        axis.title.y = element_text(size=12),
        strip.text = element_text(size=11),
        legend.justification= c(1, 0), 
        legend.position = c(0.15, 0.86),
        legend.key = element_blank(),
        legend.title = element_blank(),
        legend.text = element_text(size=11),
        legend.margin = margin(0, 0, 0, 0),
        legend.key.spacing.x = unit(0, "pt"),
        legend.key.spacing.y = unit(-6, "pt"),
        legend.spacing.y = unit(-5, "pt"),
        legend.box.spacing = unit(0, "pt"),
        legend.background = element_rect(fill=alpha(0.0001)))
```

### Calculating the fits

```{r}
fitDriftAndRewardData <- avgData %>%
  filter(driftFuncPower == "13") %>% 
  group_by(driftFuncName, power) %>% 
  summarise(
  pow=summary(nls(avgST ~ I(a*T^p), start=list(p=1, a=1), trace=F))$coefficients[1,1],
  powSE=summary(nls(avgST ~ I(a*T^p),start=list(p=1,a=1), trace=F))$coefficients[1,2],
  powSig=summary(nls(avgST~I(a*T^p),start=list(p=1,a=1), trace=F))$coefficients[1,4]<0.05,
  c=summary(nls(avgST ~ I(a*T^p), start=list(p=1, a=1), trace=F))$coefficients[2,1],
  cSE = summary(nls(avgST ~ I(a*T^p), start=list(p=1,a=1), trace=F))$coefficients[2,2],
  cSig = summary(nls(avgST~I(a*T^p),start=list(p=1,a=1), trace=F))$coefficients[2,4]<0.05,
  .groups = "drop")

fitDriftAndRewardData$pConf <- paste0(round(fitDriftAndRewardData$pow, 3), "±", round(2*fitDriftAndRewardData$powSE, 4))
fitDriftAndRewardData$cConf <- paste0(round(fitDriftAndRewardData$c, 3), "±", round(2*fitDriftAndRewardData$cSE, 4))
```

```{r}
fitDriftAndRewardData %>% 
  pivot_wider(id_cols = driftFuncName, names_from = power, values_from = c(cConf, pConf)) %>%
  kable(align = rep("c", 5), col.names = NULL) %>% 
  kable_classic() %>% 
  add_header_above(c("Drift function", rep(c("Payoff power = 2", "Payoff power = 5"), 2))) %>% 
  add_header_above(c(" ", "Constant"=2, "Order"=2))
```

```{r}
fitDriftAndRewardData %>% 
  pivot_wider(id_cols = driftFuncName, names_from = power, values_from = c(cConf, pConf)) %>%
  kable(align = rep("c", 5), col.names = NULL, linesep="", longtable=FALSE, format="latex") %>% 
  kable_classic() %>% 
  add_header_above(c("Drift function", rep(c("Payoff power = 1", "Payoff power = 5"), 2))) %>% 
  add_header_above(c(" ", "Constant"=2, "Order"=2))
```

## Number of decisions

```{r}
ggplot(avgData, aes(x=T, group=driftFuncName))+
  geom_line(aes(y=avgDataDecisionsPerTime-avgOptDecisionsPerTime, color=driftFuncName), size=1.2)+
  geom_hline(yintercept=0,linetype="dashed", alpha=0.5)+
  ylab("Difference per time in number of decisions")+
  xlab("Time horizon (T)")+
  ggtitle("Diff. in number of decisions made per time unit by optimal and data-driven strategy")+
  scale_color_manual(values = c("b1" = "#66c2a5",
                                "b2" = "#fc8d62",
                                "b3" = "#8da0cb"),
                     labels=c(TeX("$b_1$"), TeX("$b_2$"), TeX("$b_3$")))+
  labs(color = "Drift Slope")+
  facet_grid(pText ~ driftpText2, scales="fixed")+
  theme_bw()+
  scale_y_continuous(breaks = scales::pretty_breaks(n = 5))+
  theme(plot.title = element_text(face = "bold", size=13),
        axis.title.x = element_text(size=12),
        axis.title.y = element_text(size=12),
        strip.text = element_text(size=11),
        legend.justification= c(1, 0), 
        legend.position = c(0.48, 0.83),
        legend.key = element_blank(),
        legend.title = element_blank(),
        legend.text = element_text(size=11),
        legend.margin = margin(0, 0, 0, 0),
        legend.key.spacing.x = unit(0, "pt"),
        legend.key.spacing.y = unit(-6, "pt"),
        legend.spacing.y = unit(-5, "pt"),
        legend.box.spacing = unit(0, "pt"),
        legend.background = element_rect(fill=alpha(0.0001)))
```


# Thresholds

```{r}
thresholds$pText = paste0("Payoff power = ", thresholds$power)
thresholds$driftpText <- factor(paste0("Drift power = ", thresholds$driftFuncPower), levels = c("Drift power = 3", "Drift power = 13"))
thresholds$driftpText2 <- factor(paste0("m = ", thresholds$driftFuncPower), levels = c("m = 3", "m = 13"))

thresholds$driftFuncName <- as.factor(thresholds$driftFuncName)
thresholds$driftpText <- as.factor(thresholds$driftpText)
thresholds$pText <- as.factor(thresholds$pText)
```

```{r}
tmpData <- thresholds %>% filter(T == 5000)

ggplot(tmpData, aes(ST))+
  geom_histogram(bins=100, color = "#000000", fill = "#1f78b4")+
  ylab("Number of estimates made")+
  xlab("Exporation time (ST)")+
  ggtitle("Number of estimates made at different exploration times")+
  facet_grid(driftFuncName~driftpText2, scales="fixed")+
  theme_bw()+
  theme(plot.title = element_text(face = "bold", size=13),
        axis.title.x = element_text(size=12),
        axis.title.y = element_text(size=12),
        strip.text = element_text(size=11),
        legend.justification= c(1, 0), 
        legend.position = c(0.47, 0.91),
        legend.key = element_blank(),
        legend.title = element_blank(),
        legend.text = element_text(size=11),
        legend.margin = margin(0, 0, 0, 0),
        legend.key.spacing.x = unit(0, "pt"),
        legend.key.spacing.y = unit(-6, "pt"),
        legend.spacing.y = unit(-5, "pt"),
        legend.box.spacing = unit(0, "pt"),
        legend.background = element_rect(fill=alpha(0.0001)))
```

```{r}
thresholds <- thresholds %>%
  mutate(cut_number = cut_number(ST, n=5),
         diffToOptimal = yhat-y_star) %>% 
  group_by(driftFuncName, cut_number, power, driftFuncPower) %>% 
  mutate(
    upperlimit = boxplot.stats(diffToOptimal)$stats[c(1, 5)][2],
    lowerlimit = boxplot.stats(diffToOptimal)$stats[c(1, 5)][1]
  ) %>% 
  ungroup()

thresholds <- thresholds %>% mutate(isLowerOutlier = diffToOptimal<lowerlimit,
                                    isUpperOutlier = diffToOptimal>upperlimit)

loweroutliers <- thresholds %>%
  filter(diffToOptimal < lowerlimit) %>% 
  group_by(driftFuncName, cut_number, power, driftFuncPower) %>% 
  summarise(n = n(),
            avgDiff = mean(diffToOptimal),
            .groups = "drop"
            )

upperoutliers <- thresholds %>%
  filter(diffToOptimal > upperlimit) %>% 
  group_by(driftFuncName, cut_number, power, driftFuncPower) %>% 
  summarise(n = n(),
            avgDiff = mean(diffToOptimal),
            .groups = "drop"
            )

ystart_text <- thresholds %>% group_by(driftFuncName, cut_number, power, driftFuncPower) %>% 
  summarise(
    ystart_text = paste0("Opt. y = ", round(unique(y_star),2)),
    diffToOptimal = max(diffToOptimal),
    .groups = "drop"
  )

ystart_text$cut_number <- "(179,433]"


ggplot(data=thresholds, aes(cut_number, diffToOptimal))+
  geom_boxplot(aes(color=driftpText2), outliers = F, outlier.size = 0.9)+
  geom_hline(yintercept=0,linetype="dashed", alpha = 0.5)+
  ylab("Estimated threshold - Optimal threshold")+
  xlab("Exploration time interval")+
  ggtitle("Difference between estimated and optimal threshold for misspecified drifts")+
  scale_color_manual(values = c("m = 3" = "#fc8d62",
                                "m = 13" = "#8da0cb"))+
  labs(color = "Drift Slope")+
  facet_grid(pText ~ driftFuncName, scales="free")+
  theme_bw()+
  scale_y_continuous(breaks = scales::pretty_breaks(n = 5))+
  theme(plot.title = element_text(face = "bold", size=13),
        axis.title.x = element_text(size=12),
        axis.title.y = element_text(size=12),
        strip.text = element_text(size=11),
        legend.justification= c(1, 0), 
        legend.position = c(0.1, 0.91),
        legend.key = element_blank(),
        legend.title = element_blank(),
        legend.text = element_text(size=11),
        legend.margin = margin(0, 0, 0, 0),
        legend.key.spacing.x = unit(0, "pt"),
        legend.key.spacing.y = unit(-6, "pt"),
        legend.spacing.y = unit(-5, "pt"),
        legend.box.spacing = unit(0, "pt"),
        legend.background = element_rect(fill=alpha(0.0001)))
```


Lower outliers

```{r}
loweroutliersData <- thresholds %>% filter(isLowerOutlier == TRUE)
upperoutliersData <- thresholds %>% filter(isUpperOutlier == TRUE)

outliersData <- rbind(loweroutliersData, upperoutliersData)

ggplot(data=outliersData, aes(cut_number, diffToOptimal))+
  geom_boxplot(data=loweroutliersData, aes(color=driftpText2), outliers = T)+
  geom_boxplot(data=upperoutliersData, aes(color=driftpText2), outliers = T)+
  geom_hline(yintercept=0,linetype="dashed", alpha=0.5)+
  ylab("Estimated threshold - Optimal threshold")+
  xlab("Exploration time interval")+
  ggtitle("Difference between estimated and optimal threshold for misspecified drifts (Outliers)")+
  scale_color_manual(values = c("m = 3" = "#fc8d62",
                                "m = 13" = "#8da0cb"))+
  labs(color = "Drift Slope")+
  facet_grid(pText ~ driftFuncName, scales="free")+
  theme_bw()+
  scale_y_continuous(breaks = scales::pretty_breaks(n = 5))+
  theme(plot.title = element_text(face = "bold", size=13),
        axis.title.x = element_text(size=12),
        axis.title.y = element_text(size=12),
        strip.text = element_text(size=11),
        legend.justification= c(1, 0), 
        legend.position = c(0.32, 0.91),
        legend.key = element_blank(),
        legend.title = element_blank(),
        legend.text = element_text(size=11),
        legend.margin = margin(0, 0, 0, 0),
        legend.key.spacing.x = unit(0, "pt"),
        legend.key.spacing.y = unit(-6, "pt"),
        legend.spacing.y = unit(-5, "pt"),
        legend.box.spacing = unit(0, "pt"),
        legend.background = element_rect(fill=alpha(0.0001)))
```

