---
title: "Plots"
author: "Rasmus Brostrøm"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
library(dplyr)
library(stats)
```

```{r}
#setwd("C:/Projects/Data-driven-algorithms-for-Impulse-control-problem-Thesis")
setwd("C:/Uni/Data-driven-algorithms-for-Impulse-control-problem-Thesis")
thresholdData <- read.csv("./SimulationData/ThresholdData.csv")
DataStratData <- read.csv("./SimulationData/DataStratIncreasingTData.csv")
MISEData <- read.csv("./SimulationData/MISE.csv")
MISEData2 <- read.csv("./SimulationData/MISE2.csv")
MISEData3 <- read.csv("./SimulationData/MISE3.csv")
KLData <- read.csv("./SimulationData/KL.csv")
KLData2 <- read.csv("./SimulationData/KL2.csv")
thresholdDiffData <- read.csv("./SimulationData/ThresholdDiff.csv")
```


# Threshold data plot

Grouping the data by threshold and T to get average regret
```{r}
avgThreshold <- thresholdData %>%
  group_by(threshold, T) %>%
  summarise(meanRegret = mean(regret), .groups = "drop")

avgThreshold$threshold = as_factor(avgThreshold$threshold)
```

```{r}
ggplot(data = avgThreshold, aes(T, meanRegret, colour=threshold))+
  geom_line()
```

# Data driven data

Grouping the data by T to get average regret
```{r}
avgDataStrat <- DataStratData %>% 
  group_by(T) %>% 
  summarise(meanRegret = mean(regret),
            sdRegret = sd(regret),
            minRegret = min(regret),
            maxRegret = max(regret),
            meanExplorationTime = mean(S_T),
            sdExplorationTime = sd(S_T),
            .groups = "drop") %>% 
  mutate(lBound = sqrt(T),
         uBound = T^(2/3))
```

Average regret plot
```{r}
ggplot(avgDataStrat, aes(x=T))+
  geom_line(aes(y=meanRegret))+
  geom_line(aes(y=lBound, colour="red"), show.legend = FALSE)+
  geom_line(aes(y=uBound, colour="red"), show.legend = FALSE)
```

Plot the average exploration time
```{r}
ggplot(avgDataStrat, aes(x=T))+
  geom_line(aes(y=meanExplorationTime))+
  geom_line(aes(y=uBound, colour="red"), show.legend = FALSE)
```

Plot with min/max bars
```{r}
ggplot(avgDataStrat, aes(x=T, y=meanRegret))+
  geom_errorbar(aes(ymin=minRegret, ymax=maxRegret), width=100, colour="red")+
  geom_line()+
  ylab("Avg. Regret")
```


Plotting the raw simulation data with smooth
```{r}
DataStratData <- DataStratData %>% mutate(lBound = sqrt(T),
                                          uBound = T^(2/3))
```

```{r}
ggplot(DataStratData, aes(x=T))+
  geom_point(aes(y=regret))+
  geom_smooth(aes(y=regret))+
  geom_line(aes(y=lBound, colour="red"), show.legend = FALSE)+
  geom_line(aes(y=uBound, colour="red"), show.legend = FALSE)
```

```{r}
ggplot(DataStratData, aes(x=T))+
  geom_point(aes(y=S_T))+
  geom_smooth(aes(y=S_T))+
  geom_line(aes(y=uBound, colour="red"), show.legend = FALSE)
```


# Fitting to data:
```{r}
m <- nls(regret ~ I(T^power), data = DataStratData, start = list(power=1), trace = T)
```

```{r}
summary(m)
```


# MISE data plots
```{r}
avgMiseData <- MISEData %>% group_by(T) %>% summarise(avgMise = mean(MISE),
                                                      sdMise = sd(MISE),
                                                      .groups = "drop")
avgMiseData2 <- MISEData2 %>% group_by(T) %>% summarise(avgMise = mean(MISE),
                                                      sdMise = sd(MISE),
                                                      .groups = "drop")
avgMiseData3 <- MISEData3 %>% group_by(T) %>% summarise(avgMise = mean(MISE),
                                                      sdMise = sd(MISE),
                                                      .groups = "drop")
```


```{r}
ggplot(avgMiseData3, aes(x=T, y=avgMise))+
  geom_line()
```

# KL Data plot
```{r}
avgKLData <- KLData %>% group_by(T) %>% summarise(avgKL = mean(KL),
                                                  sdKL = sd(KL),
                                                  .groups = "drop")
avgKLData2 <- KLData2 %>% group_by(T) %>% summarise(avgKL = mean(KL),
                                                  sdKL = sd(KL),
                                                  .groups = "drop")
```

```{r}
ggplot(avgKLData, aes(x=T, y=avgKL))+
  geom_line()
```

```{r}
ggplot(KLData2, aes(x=T, y=KL))+
  geom_point()
```

# Threshold difference between optimal and estimated
```{r}
avgThresholdDiff <- thresholdDiffData %>% group_by(T) %>%  summarise(avgDiff = mean(SquareDiff),
                                                                     sdDiff = sd(SquareDiff),
                                                                     .groups = "drop")
```

```{r}
ggplot(avgThresholdDiff, aes(x=T, y=avgDiff))+
  geom_line()
```

